#version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ling
      - MONGO_INITDB_ROOT_PASSWORD=long

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ling
      - ME_CONFIG_MONGODB_ADMINPASSWORD=long
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  data: {}

networks:
  default:
    name: mongodb-network

#services:
#  mongodb:
#    image: mongo
#    container_name: mongo_db
#    ports:
#      - 8094:27017
#    volumes:
#      - mongo:/data
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=helaoui
#      - MONGO_INITDB_ROOT_PASSWORD=helaoui
#  mongo-express:
#    image: mongo-express
#    container_name: mongo_express
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=helaoui
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=helaoui
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#volumes:
#  mongo: { }
